// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rgAGhJIpFa2l-6zbdocFSSp8R23jIsA',
    appId: '1:102076675022:web:4d55a38da8e493aaccf19f',
    messagingSenderId: '102076675022',
    projectId: 'fir-flutter-1da36',
    authDomain: 'fir-flutter-1da36.firebaseapp.com',
    storageBucket: 'fir-flutter-1da36.appspot.com',
    measurementId: 'G-GHP6LK88P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-EeCDyFFxxff-THLRWiYdu8ClCmJpPnI',
    appId: '1:102076675022:android:8690b6b56a48a36cccf19f',
    messagingSenderId: '102076675022',
    projectId: 'fir-flutter-1da36',
    storageBucket: 'fir-flutter-1da36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEXVYHJpz8bwWUyKUmgdodFLgR0gDpTs',
    appId: '1:102076675022:ios:0bc886978e5a2616ccf19f',
    messagingSenderId: '102076675022',
    projectId: 'fir-flutter-1da36',
    storageBucket: 'fir-flutter-1da36.appspot.com',
    iosClientId: '102076675022-5autfkb7ornuks7eps3stqghmq1ifbn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEXVYHJpz8bwWUyKUmgdodFLgR0gDpTs',
    appId: '1:102076675022:ios:0bc886978e5a2616ccf19f',
    messagingSenderId: '102076675022',
    projectId: 'fir-flutter-1da36',
    storageBucket: 'fir-flutter-1da36.appspot.com',
    iosClientId: '102076675022-5autfkb7ornuks7eps3stqghmq1ifbn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
